/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bil481Proje2;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }

    public static boolean isBigger(int num1, int num2, int num3, int[] arr){
        // if array has num1, num2 and sum of these numbers are bigger than num3 return true, if not false
        boolean num1v = false;
        boolean num2v = false;
        for(int i=0; i<arr.length; i++){
            if(arr[i] == num1){
                num1v = true;    
            }
            if(arr[i] == num2){
                num2v = true;
            }
        }
        if(num1v == true && num2v == true){
            if(num1+num2 > num3){
                return true;
            }
            else
                return false;
        }
        return false;
    }

}
