/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bil481Proje2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test public void num1Notnum2(){
        int[] numArray = new int[5];
        numArray[0] = 5;numArray[1] = 7;numArray[2] = 2;numArray[3] = 9;numArray[4] = 12;
        assertFalse(App.isBigger(7, 4, 3, numArray));
    }

    @Test
    public void Notnum1num2(){
        int[] numArray = new int[5];
        numArray[0] = 5;numArray[1] = 7;numArray[2] = 2;numArray[3] = 9;numArray[4] = 12;
        assertFalse(App.isBigger(4, 7, 3, numArray));
    }

    @Test
    public void Notnum1Notnum2(){
        int[] numArray = new int[5];
        numArray[0] = 5;numArray[1] = 7;numArray[2] = 2;numArray[3] = 9;numArray[4] = 12;
        assertFalse(App.isBigger(0, 4, 3, numArray));
    }

    @Test
    public void num1num2smaller(){
        int[] numArray = new int[5];
        numArray[0] = 5;numArray[1] = 7;numArray[2] = 2;numArray[3] = 9;numArray[4] = 12;
        assertFalse(App.isBigger(2, 9, 13, numArray));
    }

    @Test
    public void num1num2bigger(){
        int[] numArray = new int[5];
        numArray[0] = 5;numArray[1] = 7;numArray[2] = 2;numArray[3] = 9;numArray[4] = 12;
        assertTrue(App.isBigger(7, 5, 8, numArray));
    }
}
