/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bil481Proje2;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
    @Test public void num1Notnum2(){
        ArrayList<Integer> numArray = new ArrayList<Integer>();
        numArray.add(5);numArray.add(7);numArray.add(2);numArray.add(9);numArray.add(12);
        assertFalse(App.isBigger(7, 4, 3, numArray));
    }

    @Test
    public void Notnum1num2(){
        ArrayList<Integer> numArray = new ArrayList<Integer>();
        numArray.add(5);numArray.add(7);numArray.add(2);numArray.add(9);numArray.add(12);
        assertFalse(App.isBigger(4, 7, 3, numArray));
    }

    @Test
    public void Notnum1Notnum2(){
        ArrayList<Integer> numArray = new ArrayList<Integer>();
        numArray.add(5);numArray.add(7);numArray.add(2);numArray.add(9);numArray.add(12);
        assertFalse(App.isBigger(0, 4, 3, numArray));
    }

    @Test
    public void num1num2smaller(){
        ArrayList<Integer> numArray = new ArrayList<Integer>();
        numArray.add(5);numArray.add(7);numArray.add(2);numArray.add(9);numArray.add(12);
        assertFalse(App.isBigger(2, 9, 13, numArray));
    }

    @Test
    public void num1num2bigger(){
        ArrayList<Integer> numArray = new ArrayList<Integer>();
        numArray.add(5);numArray.add(7);numArray.add(2);numArray.add(9);numArray.add(12);
        assertTrue(App.isBigger(7, 5, 8, numArray));
    }
}
